# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    scrape_interval: 5s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.1.240:9100']
      - targets: ['192.168.1.241:9100']
      - targets: ['192.168.1.242:9100']

  - job_name: 'arm-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.1.240:9243']
      - targets: ['192.168.1.241:9243']
      - targets: ['192.168.1.242:9243']

  - job_name: 'kube-scheduler'
    static_configs:
      - targets: ['scheduler-service.kube-system.svc.cluster.local:10251']
